version: '3.1'
services:
  postgres:
    image: postgres_tr:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
      # If you want to change the default collation of Postgres you can use the following. [optional]
      #POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=tr_TR.UTF-8 --lc-ctype=tr_TR.UTF-8'
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres:
